### ISSUE TITLE
Perform checklist operations on Send Transaction page

### ISSUE THREAD

**Issue by jaa2** [jaa2/ethereum-web-wallet#149]
Currently, all the items in the transaction checklist must resolve before the user goes from the Create Transaction page to the Send Transaction page. This causes a delay in the flow.

- [ ] Move the transaction checklist operations from the Create Transaction page to the Send Transaction page
- [ ] Assign a spinner to each checklist item until it resolves
- [ ] Decide whether the simulation passed or failed after all items have resolved

An `estimateGas` call is still needed before going to the Send Transaction page, but waiting for only one is better than waiting for all the RPC calls.
